# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
import numpy as np

arr1=np.random.randint(1,20,size=(5,5))
print(arr1)

arr1[:,2]=1
print(arr1)

[[13  9  4 16 17]
 [10 13 10  7  3]
 [ 7  9  9  4 13]
 [11  5 12 13 10]
 [10 16 16 17 18]]
[[13  9  1 16 17]
 [10 13  1  7  3]
 [ 7  9  1  4 13]
 [11  5  1 13 10]
 [10 16  1 17 18]]


In [11]:
arr12=np.arange(1,17).reshape(4,4)
print(arr12)

np.fill_diagonal(arr12,0)
print(arr12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [21]:
arr2=np.arange(1,37).reshape(6,6)
print(arr2)

print('sub array: ',arr2[2:5,1:4])

arr22=np.random.randint(100,size=(5,5))
print(arr22)

print('border elements:',arr22[0,:],arr22[4,:],arr22[:,0],arr22[:,4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
sub array:  [[14 15 16]
 [20 21 22]
 [26 27 28]]
[[ 1 89 10 31 65]
 [37 19 19 60 50]
 [94 37 10 66 79]
 [76  2 99 53 92]
 [59 98 74 52  0]]
border elements: [ 1 89 10 31 65] [59 98 74 52  0] [ 1 37 94 76 59] [65 50 79 92  0]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [22]:
arr3=np.random.randint(1,100,size=(3,4))
arr_3=np.random.randint(1,100,size=(3,4))

add=arr3+arr_3
print(add)
sub=arr3-arr_3
print(sub)
mul=arr3*arr_3
print(mul)
div=arr3/arr_3
print(div)

[[ 97  71  26 106]
 [140 170 109 111]
 [ 73  58  88 153]]
[[ 59 -29  24  -2]
 [ -8  14 -67  37]
 [ 35  48  20 -23]]
[[1482 1050   25 2808]
 [4884 7176 1848 2738]
 [1026  265 1836 5720]]
[[ 4.10526316  0.42       25.          0.96296296]
 [ 0.89189189  1.17948718  0.23863636  2.        ]
 [ 2.84210526 10.6         1.58823529  0.73863636]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [29]:
arr32=np.arange(1,17).reshape(4,4)
print(arr32)

row_sum=np.sum(arr32,axis=1)
col_sum=np.sum(arr32,axis=0)

print('row_sum',row_sum)
print('col_sum',col_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_sum [10 26 42 58]
col_sum [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [33]:
arr4=np.random.randint(1,100,size=(5,5))
print(arr4)

mean=np.mean(arr4)
print(mean)
median=np.median(arr4)
print(median)
std_dev=np.std(arr4)
print(std_dev)
variance=np.var(arr4)
print(variance)

[[22 71 19 15 69]
 [57 82 60 11 80]
 [62 91 19 87 18]
 [89 76 74 84 17]
 [98 67 74 88 12]]
57.68
69.0
29.76268805064489
885.8176000000001


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [35]:
arr42=np.arange(1,10).reshape(3,3)
print(arr42)

mean=np.mean(arr42)
std_dev=np.std(arr42)
normalize=(arr42-mean)/std_dev
print(normalize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [38]:
arr5=np.random.randint(1,100,size=(3,3))
print(arr5)
arr_5=np.random.randint(1,100,size=(3,))
print(arr_5)

result=arr5+arr_5
print('result',result)

[[96 28 69]
 [50 12 46]
 [41 87 71]]
[21 26 56]
result [[117  54 125]
 [ 71  38 102]
 [ 62 113 127]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [40]:
arr52=np.random.randint(1,100,size=(4,4))
print(arr52)
arr_52=np.random.randint(1,11,size=(4,))
print(arr_52)

result=arr52-arr_52
print('result:')
print(result)

[[21 66 37 77]
 [ 2 51 70 28]
 [68 12  3 87]
 [94  5 79 26]]
[ 9  2  6 10]
result:
[[12 64 31 67]
 [-7 49 64 18]
 [59 10 -3 77]
 [85  3 73 16]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [46]:
arr6=np.random.randint(1,11,size=(3,3))
print('arr6')
print(arr6)
determinant=np.linalg.det(arr6)
print('determinant: ',determinant)

inverse=np.linalg.inv(arr6)
print('inverse of arr6:\n',inverse)

eigenvalues=np.linalg.eigvals(arr6)
print('Eigen values of arr6\n',eigenvalues)

arr6
[[1 4 1]
 [8 1 6]
 [2 1 3]]
determinant:  -44.99999999999999
inverse of arr6:
 [[ 0.06666667  0.24444444 -0.51111111]
 [ 0.26666667 -0.02222222 -0.04444444]
 [-0.13333333 -0.15555556  0.68888889]]
Eigen values of arr6
 [ 8.31717355 -4.51540353  1.19822998]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [47]:
arr62=np.random.randint(1,11,size=(2,3))
print('arr62:\n',arr62)
arr_62=np.random.randint(1,11,size=(3,2))
print('arr_62:\n',arr_62)

mul=np.dot(arr62,arr_62)
print('Multiplied array:\n',mul)

arr62:
 [[7 9 1]
 [3 5 8]]
arr_62:
 [[2 2]
 [7 6]
 [9 1]]
Multiplied array:
 [[ 86  69]
 [113  44]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [48]:
arr7=np.arange(1,10).reshape(3,3)
print('Original:\n',arr7)

arr7=arr7.reshape(1,9)
print('modification 1:\n',arr7)

arr7=arr7.reshape(9,1)
print('modificcation 2:\n',arr7)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
modification 1:
 [[1 2 3 4 5 6 7 8 9]]
modificcation 2:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [50]:
arr72=np.random.randint(1,11,size=(5,5))
print('original:\n',arr72)

arr72=arr72.flatten()
print('Modification1:\n',arr72)

arr72=arr72.reshape(5,5)
print('Modification2:\n',arr72)

original:
 [[ 3  1  5 10  5]
 [ 1  1  3  1  8]
 [ 5  9  9  6  8]
 [ 6  9  5  6  5]
 [ 2 10  7  4  7]]
Modification1:
 [ 3  1  5 10  5  1  1  3  1  8  5  9  9  6  8  6  9  5  6  5  2 10  7  4
  7]
Modification2:
 [[ 3  1  5 10  5]
 [ 1  1  3  1  8]
 [ 5  9  9  6  8]
 [ 6  9  5  6  5]
 [ 2 10  7  4  7]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [53]:
arr8=np.random.randint(1,11,size=(5,5))
print('arr8:\n',arr8)

corner=arr8[[0,0,-1,-1],[0,-1,-1,0]]
print('corner:\n',corner)

arr8:
 [[10  4  6  6  8]
 [ 3  2  4  4  6]
 [ 4  5  4  2  7]
 [ 1 10  7 10  5]
 [ 2  5 10  2  9]]
corner:
 [10  8  9  2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [57]:
arr82=np.random.randint(1,100,size=(4,4))
print('arr82:\n',arr82)

mask=arr82>10
arr82[mask]=10
print(arr82)

arr82:
 [[23 15 26 65]
 [91 33 74 53]
 [25 81 90 38]
 [ 4 41 72 40]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [ 4 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [58]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [63]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(2,3),(5,3),(8,10)],dtype=data_type)
print('data:\n',data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

data:
 [(2,  3) (5,  3) (8, 10)]
Euclidean distances:
[[0.         3.         9.21954446]
 [3.         0.         7.61577311]
 [9.21954446 7.61577311 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.