In [1]:
import numpy as np

# create array using np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6) #1 row 6 col

array([[1, 2, 3, 4, 5, 6]])

In [3]:
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [4]:
arr4=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr4)
arr4.shape

[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
## Attributes of numpy array

print('Array:\n',arr4)
print("Shape: ",arr4.shape)
print('no od dimension: ',arr4.ndim)
print('size (no of elements): ',arr4.size)
print('Data Type: ',arr4.dtype)
print('Item size (in bytes): ',arr4.itemsize)

Array:
 [[1 2 3 4 5]
 [6 7 8 9 0]]
Shape:  (2, 5)
no od dimension:  2
size (no of elements):  10
Data Type:  int64
Item size (in bytes):  8


In [9]:
## Numpy Vectorized operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element wise addition
print('Addition: ',arr2+arr1)

# Element wise substraction
print('Addition: ',arr2-arr1)

# Element wise multiplication
print('Addition: ',arr2*arr1)

# Element wise divison
print('Addition: ',arr2/arr1)

Addition:  [11 22 33 44 55]
Addition:  [ 9 18 27 36 45]
Addition:  [ 10  40  90 160 250]
Addition:  [10. 10. 10. 10. 10.]


In [10]:
## Universal Function

arr=np.array([2,3,4,5,6])

##sqr root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [11]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print(arr[0][0])

1


In [13]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [14]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
## Modify array Elements
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [17]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [18]:
## Statistical concepts --Normalization
## have meam of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

# normalizing the data
normalized_data=(data-mean)/std_dev
print('Normalized data:',normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean=np.mean(data)
print('Mean: ',mean)

#median
median=np.median(data)
print('Median: ',median)

# Std deviation
std_dev=np.std(data)
print('Standard Deviation: ',std_dev)

#variance
variance=np.var(data)
print('Variance:',variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance: 8.25


In [20]:
## Logical operation

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
data[(data>5) & (data<8)]

array([6, 7])